/**
 * Residential building typology catalog for the English-speaking world.
 * Names follow US usage first; regionalNames give UK / CA / AU / NZ / IE terms.
 * All dimensions in metres. These are DEFAULTS — the spec can override any of them.
 */
import type { TypologyDef, TypologyId } from './types.ts';

export const TYPOLOGIES: Record<TypologyId, TypologyDef> = {
  'detached-house': {
    id: 'detached-house',
    name: 'Single-family detached house',
    regionalNames: { UK: 'Detached house', AU: 'Freestanding house', NZ: 'Standalone house', CA: 'Single-detached house', IE: 'Detached house' },
    description: 'One dwelling on its own lot with garden on all sides. 1–3 storeys, private entry and garage/driveway.',
    access: 'direct',
    footprintShapes: ['bar', 'L', 'T'],
    storeys: { min: 1, max: 3, default: 2 },
    floorToFloor: { typical: 2.9, ground: 3.0 },
    buildingDepth: { min: 8, max: 14, default: 11 },
    unitsPerFloor: { min: 1, max: 1 },
    defaultUnitMix: { 'colonial-4b': 1 },
    parking: 'garage-attached',
    parkingRatio: 2,
    bikeRatio: 2,
    setbacks: { front: 6.0, side: 1.5, rear: 7.5 },
    structure: 'light-wood-frame',
    foundation: 'strip-footing',
    hvac: 'ducted-heat-pump',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tank',
    sprinklered: false,
    elevator: false,
    density: { min: 8, max: 25 },
    patterns: ['SIT-01', 'SIT-04', 'ARC-01', 'ARC-10', 'ARC-11'],
  },
  'adu-laneway': {
    id: 'adu-laneway',
    name: 'Accessory dwelling unit (ADU)',
    regionalNames: { UK: 'Annexe / garden flat', AU: 'Granny flat', CA: 'Laneway house', NZ: 'Minor dwelling', IE: 'Garden studio' },
    description: 'A small secondary dwelling at the rear of a lot, 1–2 storeys, often over or beside a garage.',
    access: 'direct',
    footprintShapes: ['bar'],
    storeys: { min: 1, max: 2, default: 1 },
    floorToFloor: { typical: 2.8, ground: 2.9 },
    buildingDepth: { min: 6, max: 9, default: 7.5 },
    unitsPerFloor: { min: 1, max: 1 },
    defaultUnitMix: { 'adu-1b': 1 },
    parking: 'surface',
    parkingRatio: 1,
    bikeRatio: 1,
    setbacks: { front: 1.5, side: 1.2, rear: 1.2 },
    structure: 'light-wood-frame',
    foundation: 'slab-on-grade',
    hvac: 'ductless-mini-split',
    ventilation: 'exhaust-only',
    dhw: 'per-unit-tankless',
    sprinklered: false,
    elevator: false,
    density: { min: 20, max: 40 },
    patterns: ['SIT-05', 'ARC-01', 'ARC-10'],
  },
  'semi-detached': {
    id: 'semi-detached',
    name: 'Semi-detached / side-by-side duplex',
    regionalNames: { US: 'Duplex (side-by-side)', UK: 'Semi-detached house', AU: 'Duplex', CA: 'Semi-detached', NZ: 'Duplex', IE: 'Semi-detached house' },
    description: 'Two mirrored dwellings sharing one party wall, each with its own entry and garden.',
    access: 'direct',
    footprintShapes: ['bar'],
    storeys: { min: 2, max: 3, default: 2 },
    floorToFloor: { typical: 2.8, ground: 2.9 },
    buildingDepth: { min: 8, max: 12, default: 10 },
    unitsPerFloor: { min: 2, max: 2 },
    defaultUnitMix: { 'townhouse-2s': 1 },
    parking: 'surface',
    parkingRatio: 1.5,
    bikeRatio: 2,
    setbacks: { front: 5.0, side: 1.5, rear: 7.0 },
    structure: 'masonry-bearing',
    foundation: 'strip-footing',
    hvac: 'ducted-heat-pump',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tank',
    sprinklered: false,
    elevator: false,
    density: { min: 20, max: 40 },
    patterns: ['SIT-01', 'ARC-01', 'ARC-02', 'ARC-10'],
  },
  'townhouse-row': {
    id: 'townhouse-row',
    name: 'Townhouse row',
    regionalNames: { US: 'Townhomes / rowhouses', UK: 'Terraced houses', AU: 'Terrace houses / townhouses', CA: 'Row houses', NZ: 'Terraced housing', IE: 'Terraced houses' },
    description: 'A row of 3–12 attached dwellings, each 2–4 storeys with its own front door, party walls between.',
    access: 'direct',
    footprintShapes: ['bar'],
    storeys: { min: 2, max: 4, default: 3 },
    floorToFloor: { typical: 2.9, ground: 3.0 },
    buildingDepth: { min: 9, max: 13, default: 11 },
    unitsPerFloor: { min: 3, max: 12 },
    defaultUnitMix: { 'townhouse-3s': 1 },
    parking: 'garage-attached',
    parkingRatio: 1,
    bikeRatio: 2,
    setbacks: { front: 3.0, side: 1.5, rear: 6.0 },
    structure: 'light-wood-frame',
    foundation: 'strip-footing',
    hvac: 'ducted-heat-pump',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tankless',
    sprinklered: true,
    elevator: false,
    density: { min: 40, max: 90 },
    patterns: ['SIT-01', 'SIT-02', 'ARC-01', 'ARC-02', 'ARC-10', 'XD-01', 'XD-03'],
  },
  'stacked-townhouse': {
    id: 'stacked-townhouse',
    name: 'Stacked flats',
    regionalNames: { US: 'Triple-decker / two-flat', UK: 'Tyneside flats / maisonettes', CA: 'Stacked townhouses', AU: 'Walk-up flats', IE: 'Duplex over apartment' },
    description: 'Two or three dwellings stacked in one house-like volume, each with its own street door and a private stair.',
    access: 'direct',
    footprintShapes: ['bar'],
    storeys: { min: 2, max: 4, default: 3 },
    floorToFloor: { typical: 2.9, ground: 3.0 },
    buildingDepth: { min: 10, max: 14, default: 12 },
    unitsPerFloor: { min: 2, max: 8 },
    defaultUnitMix: { '2b1b': 2, 'maisonette-2s': 1 },
    parking: 'surface',
    parkingRatio: 1,
    bikeRatio: 1.5,
    setbacks: { front: 3.0, side: 1.5, rear: 6.0 },
    structure: 'light-wood-frame',
    foundation: 'strip-footing',
    hvac: 'ductless-mini-split',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tank',
    sprinklered: true,
    elevator: false,
    density: { min: 60, max: 120 },
    patterns: ['ARC-01', 'ARC-02', 'XD-01', 'XD-03'],
  },
  'garden-walkup': {
    id: 'garden-walkup',
    name: 'Garden apartment walk-up',
    regionalNames: { US: 'Garden apartments / walk-up', UK: 'Low-rise flats (common stair)', AU: 'Walk-up flats', CA: 'Low-rise walk-up', IE: 'Low-rise apartments' },
    description: '3–4 storey blocks with open stair cores each serving 2–4 units per landing, no corridor, no lift.',
    access: 'stair-core',
    footprintShapes: ['bar', 'L', 'U'],
    storeys: { min: 2, max: 4, default: 3 },
    floorToFloor: { typical: 3.0, ground: 3.0 },
    buildingDepth: { min: 12, max: 16, default: 14 },
    unitsPerFloor: { min: 4, max: 16 },
    unitsPerCore: 4,
    defaultUnitMix: { '1b1b': 2, '2b1b': 3, '2b2b': 2, 'studio': 1 },
    parking: 'surface',
    parkingRatio: 1.2,
    bikeRatio: 1,
    setbacks: { front: 6.0, side: 3.0, rear: 6.0 },
    structure: 'light-wood-frame',
    foundation: 'strip-footing',
    hvac: 'ductless-mini-split',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tank',
    sprinklered: true,
    elevator: false,
    density: { min: 60, max: 120 },
    patterns: ['SIT-02', 'ARC-04', 'ARC-05', 'XD-01', 'XD-03', 'XD-04'],
  },
  'mansion-block': {
    id: 'mansion-block',
    name: 'Mansion block',
    regionalNames: { US: 'Pre-war apartment house', UK: 'Mansion block', AU: 'Art-deco flats', CA: 'Low-rise apartment', IE: 'Mansion flats' },
    description: 'Generous 2-per-landing flats around a stair-and-lift core, 4–7 storeys, dual-aspect units.',
    access: 'stair-core',
    footprintShapes: ['bar', 'U', 'O'],
    storeys: { min: 4, max: 7, default: 5 },
    floorToFloor: { typical: 3.2, ground: 3.6 },
    buildingDepth: { min: 14, max: 18, default: 16 },
    unitsPerFloor: { min: 2, max: 8 },
    unitsPerCore: 2,
    defaultUnitMix: { '2b2b': 2, '3b2b': 2, 'corner-2b2b': 1 },
    parking: 'underground',
    parkingRatio: 0.7,
    bikeRatio: 1.5,
    setbacks: { front: 3.0, side: 3.0, rear: 8.0 },
    structure: 'rc-flat-slab',
    foundation: 'pad-footing',
    hvac: 'mvhr-radiators',
    ventilation: 'mvhr-per-unit',
    dhw: 'heat-network',
    sprinklered: true,
    elevator: true,
    density: { min: 100, max: 200 },
    patterns: ['ARC-04', 'ARC-06', 'ARC-07', 'XD-01', 'XD-03', 'XD-04'],
  },
  'corridor-midrise': {
    id: 'corridor-midrise',
    name: 'Mid-rise double-loaded corridor',
    regionalNames: { US: '5-over-1 / mid-rise apartments', UK: 'Block of flats (corridor access)', AU: 'Mid-rise apartments', CA: 'Mid-rise condo', IE: 'Apartment block' },
    description: 'Units on both sides of a central corridor, 4–8 storeys, one or two stair/lift cores, often on a podium.',
    access: 'corridor-double',
    footprintShapes: ['bar', 'L', 'U'],
    storeys: { min: 4, max: 8, default: 6 },
    floorToFloor: { typical: 3.1, ground: 4.2 },
    buildingDepth: { min: 18, max: 24, default: 20 },
    unitsPerFloor: { min: 8, max: 30 },
    corridorWidth: 1.7,
    defaultUnitMix: { 'studio': 2, '1b1b': 4, '2b2b': 3, '3b2b': 1, 'corner-2b2b': 1 },
    parking: 'podium',
    parkingRatio: 1.0,
    bikeRatio: 1,
    setbacks: { front: 3.0, side: 3.0, rear: 6.0 },
    structure: 'wood-over-podium',
    foundation: 'pad-footing',
    hvac: 'ducted-heat-pump',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tank',
    sprinklered: true,
    elevator: true,
    density: { min: 120, max: 250 },
    patterns: ['ARC-03', 'ARC-04', 'ARC-05', 'ARC-08', 'XD-01', 'XD-02', 'XD-03', 'XD-04'],
  },
  'deck-access': {
    id: 'deck-access',
    name: 'Single-loaded / deck access',
    regionalNames: { US: 'Single-loaded corridor / breezeway', UK: 'Deck access', AU: 'Gallery access', CA: 'Single-loaded', IE: 'Deck access' },
    description: 'All units on one side of an open gallery or single-loaded corridor, so every unit is dual-aspect and cross-ventilated.',
    access: 'gallery',
    footprintShapes: ['bar', 'L'],
    storeys: { min: 3, max: 8, default: 5 },
    floorToFloor: { typical: 3.0, ground: 3.6 },
    buildingDepth: { min: 10, max: 14, default: 12 },
    unitsPerFloor: { min: 4, max: 16 },
    corridorWidth: 1.5,
    defaultUnitMix: { '1b1b': 3, '2b1b': 3, '3b2b': 2, 'maisonette-2s': 1 },
    parking: 'surface',
    parkingRatio: 0.8,
    bikeRatio: 1.5,
    setbacks: { front: 3.0, side: 3.0, rear: 6.0 },
    structure: 'mass-timber-clt',
    foundation: 'pad-footing',
    hvac: 'mvhr-radiators',
    ventilation: 'mvhr-per-unit',
    dhw: 'heat-network',
    sprinklered: true,
    elevator: true,
    density: { min: 100, max: 180 },
    patterns: ['ARC-03', 'ARC-06', 'ARC-09', 'XD-01', 'XD-02', 'XD-03'],
  },
  'courtyard-block': {
    id: 'courtyard-block',
    name: 'Courtyard / perimeter block',
    regionalNames: { US: 'Courtyard apartments', UK: 'Perimeter block', AU: 'Courtyard apartments', CA: 'Courtyard block', IE: 'Perimeter block' },
    description: 'Bars wrapping a shared landscaped courtyard, 4–8 storeys, corridor or stair-core access, dual-aspect corners.',
    access: 'corridor-double',
    footprintShapes: ['O', 'U', 'L'],
    storeys: { min: 4, max: 8, default: 6 },
    floorToFloor: { typical: 3.1, ground: 4.0 },
    buildingDepth: { min: 16, max: 20, default: 18 },
    unitsPerFloor: { min: 12, max: 60 },
    corridorWidth: 1.7,
    defaultUnitMix: { '1b1b': 3, '2b2b': 4, '3b2b': 2, 'corner-2b2b': 2, 'studio': 1 },
    parking: 'underground',
    parkingRatio: 0.8,
    bikeRatio: 1.5,
    setbacks: { front: 0.0, side: 0.0, rear: 0.0 },
    structure: 'rc-flat-slab',
    foundation: 'raft',
    hvac: 'vrf',
    ventilation: 'erv-per-unit',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 150, max: 300 },
    patterns: ['SIT-03', 'ARC-03', 'ARC-04', 'ARC-07', 'XD-01', 'XD-02', 'XD-03', 'XD-04'],
  },
  'point-tower': {
    id: 'point-tower',
    name: 'Point tower',
    regionalNames: { US: 'High-rise point tower', UK: 'Point block', AU: 'Residential tower', CA: 'Point tower (Vancouverism)', IE: 'Point block' },
    description: 'Compact square-ish floor plate around a central core with 4–8 units per floor, 10–40 storeys.',
    access: 'point-core',
    footprintShapes: ['point'],
    storeys: { min: 8, max: 45, default: 20 },
    floorToFloor: { typical: 3.0, ground: 4.5 },
    buildingDepth: { min: 24, max: 32, default: 28 },
    unitsPerFloor: { min: 4, max: 8 },
    unitsPerCore: 6,
    defaultUnitMix: { '1b1b': 3, '2b2b': 2, 'corner-2b2b': 2, 'studio': 1 },
    parking: 'underground',
    parkingRatio: 0.6,
    bikeRatio: 1.2,
    setbacks: { front: 4.0, side: 6.0, rear: 6.0 },
    structure: 'rc-flat-plate-core',
    foundation: 'piles',
    hvac: 'vrf',
    ventilation: 'central-doas',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 300, max: 800 },
    patterns: ['ARC-04', 'ARC-07', 'STR-05', 'XD-01', 'XD-04'],
  },
  'slab-tower': {
    id: 'slab-tower',
    name: 'Slab block',
    regionalNames: { US: 'High-rise slab', UK: 'Slab block', AU: 'Residential slab tower', CA: 'Slab tower', IE: 'Slab block' },
    description: 'A tall double-loaded bar, 10–25 storeys, two cores, 10–20 units per floor.',
    access: 'corridor-double',
    footprintShapes: ['bar'],
    storeys: { min: 9, max: 25, default: 14 },
    floorToFloor: { typical: 3.0, ground: 4.5 },
    buildingDepth: { min: 18, max: 22, default: 20 },
    unitsPerFloor: { min: 8, max: 20 },
    corridorWidth: 1.8,
    defaultUnitMix: { 'studio': 2, '1b1b': 4, '2b2b': 3, '3b2b': 1, 'corner-2b2b': 1 },
    parking: 'underground',
    parkingRatio: 0.6,
    bikeRatio: 1.2,
    setbacks: { front: 4.0, side: 6.0, rear: 8.0 },
    structure: 'rc-flat-plate-core',
    foundation: 'piles',
    hvac: 'central-ahu-fan-coil',
    ventilation: 'central-doas',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 250, max: 600 },
    patterns: ['ARC-03', 'ARC-04', 'ARC-05', 'XD-01', 'XD-02', 'XD-03', 'XD-04'],
  },
  'podium-tower': {
    id: 'podium-tower',
    name: 'Podium and tower',
    regionalNames: { US: 'Podium tower', UK: 'Podium block with tower', AU: 'Podium tower', CA: 'Podium tower', IE: 'Podium and tower' },
    description: 'A 2–5 storey podium (retail, amenity, parking) with a residential tower rising from it.',
    access: 'point-core',
    footprintShapes: ['point'],
    storeys: { min: 10, max: 40, default: 18 },
    floorToFloor: { typical: 3.0, ground: 5.0 },
    buildingDepth: { min: 24, max: 30, default: 26 },
    unitsPerFloor: { min: 4, max: 8 },
    unitsPerCore: 6,
    defaultUnitMix: { 'studio': 1, '1b1b': 3, '2b2b': 2, 'corner-2b2b': 2 },
    parking: 'podium',
    parkingRatio: 0.7,
    bikeRatio: 1.2,
    setbacks: { front: 0.0, side: 3.0, rear: 6.0 },
    structure: 'rc-flat-plate-core',
    foundation: 'piles',
    hvac: 'vrf',
    ventilation: 'central-doas',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 300, max: 800 },
    patterns: ['SIT-06', 'ARC-04', 'ARC-07', 'STR-04', 'STR-05', 'XD-01', 'XD-03', 'XD-04'],
  },
  'coliving-cluster': {
    id: 'coliving-cluster',
    name: 'Co-living cluster',
    regionalNames: { US: 'Co-living', UK: 'Co-living / HMO cluster flats', AU: 'Co-living / boarding house', CA: 'Co-living', IE: 'Shared living' },
    description: 'Clusters of 4–8 private ensuite rooms around a shared kitchen-living, with building-wide amenity.',
    access: 'cluster',
    footprintShapes: ['bar', 'L'],
    storeys: { min: 3, max: 8, default: 5 },
    floorToFloor: { typical: 3.0, ground: 3.6 },
    buildingDepth: { min: 16, max: 20, default: 18 },
    unitsPerFloor: { min: 2, max: 6 },
    corridorWidth: 1.6,
    defaultUnitMix: { 'coliving-cluster': 1 },
    parking: 'none',
    parkingRatio: 0.1,
    bikeRatio: 1,
    setbacks: { front: 2.0, side: 3.0, rear: 5.0 },
    structure: 'mass-timber-clt',
    foundation: 'pad-footing',
    hvac: 'mvhr-radiators',
    ventilation: 'mvhr-per-unit',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 300, max: 700 },
    patterns: ['ARC-03', 'ARC-12', 'XD-01', 'XD-02', 'XD-05'],
  },
  'senior-living': {
    id: 'senior-living',
    name: 'Senior / assisted living',
    regionalNames: { US: 'Independent / assisted living', UK: 'Extra-care housing / retirement living', AU: 'Retirement village apartments', CA: 'Seniors residence', IE: 'Retirement living' },
    description: 'Accessible one-bed units off wide corridors with dining hall, lounges and care support on the ground floor.',
    access: 'corridor-double',
    footprintShapes: ['bar', 'L', 'U'],
    storeys: { min: 2, max: 6, default: 4 },
    floorToFloor: { typical: 3.2, ground: 4.0 },
    buildingDepth: { min: 18, max: 22, default: 20 },
    unitsPerFloor: { min: 8, max: 24 },
    corridorWidth: 2.0,
    defaultUnitMix: { 'senior-1b-accessible': 4, '2b2b': 1, 'studio': 1 },
    parking: 'surface',
    parkingRatio: 0.5,
    bikeRatio: 0.2,
    setbacks: { front: 6.0, side: 4.0, rear: 6.0 },
    structure: 'wood-over-podium',
    foundation: 'pad-footing',
    hvac: 'ptac',
    ventilation: 'central-doas',
    dhw: 'central-plant',
    sprinklered: true,
    elevator: true,
    density: { min: 80, max: 200 },
    patterns: ['ARC-03', 'ARC-04', 'ARC-13', 'XD-01', 'XD-02', 'XD-04'],
  },
  'mixed-use-midrise': {
    id: 'mixed-use-midrise',
    name: 'Mixed-use mid-rise',
    regionalNames: { US: 'Mixed-use (retail over residential)', UK: 'Flats over shops', AU: 'Shop-top housing', CA: 'Mixed-use mid-rise', IE: 'Living over the shop' },
    description: 'Active ground floor retail with 3–7 residential floors above on a double-loaded corridor.',
    access: 'corridor-double',
    footprintShapes: ['bar', 'L'],
    storeys: { min: 3, max: 8, default: 5 },
    floorToFloor: { typical: 3.1, ground: 4.5 },
    buildingDepth: { min: 18, max: 24, default: 20 },
    unitsPerFloor: { min: 6, max: 24 },
    corridorWidth: 1.7,
    defaultUnitMix: { 'studio': 2, '1b1b': 4, '2b2b': 3, 'loft-live-work': 1 },
    parking: 'underground',
    parkingRatio: 0.5,
    bikeRatio: 1.2,
    setbacks: { front: 0.0, side: 0.0, rear: 5.0 },
    structure: 'wood-over-podium',
    foundation: 'pad-footing',
    hvac: 'ducted-heat-pump',
    ventilation: 'erv-per-unit',
    dhw: 'per-unit-tankless',
    sprinklered: true,
    elevator: true,
    density: { min: 120, max: 300 },
    patterns: ['SIT-06', 'ARC-03', 'ARC-04', 'ARC-08', 'STR-04', 'XD-01', 'XD-02', 'XD-03', 'XD-04'],
  },
};

export const TYPOLOGY_IDS = Object.keys(TYPOLOGIES) as TypologyId[];

export function getTypology(id: TypologyId): TypologyDef {
  const t = TYPOLOGIES[id];
  if (!t) throw new Error(`Unknown typology: ${id}`);
  return t;
}

/** Storey-count driven structural system override (used when the spec storeys leave the typology's default range) */
export function structuralSystemFor(typology: TypologyDef, storeys: number): TypologyDef['structure'] {
  if (storeys <= 3 && (typology.access === 'direct' || typology.access === 'stair-core')) return typology.structure;
  if (storeys <= 5) return typology.structure === 'rc-flat-slab' || typology.structure === 'rc-flat-plate-core' ? typology.structure : 'wood-over-podium';
  if (storeys <= 12) return typology.structure === 'mass-timber-clt' ? 'mass-timber-clt' : 'rc-flat-slab';
  return 'rc-flat-plate-core';
}

export function foundationFor(system: TypologyDef['structure'], storeys: number, parking: TypologyDef['parking']): TypologyDef['foundation'] {
  if (storeys > 12 || parking === 'underground' && storeys > 8) return 'piles';
  if (storeys > 6) return 'raft';
  if (system === 'light-wood-frame' || system === 'masonry-bearing') return storeys <= 1 ? 'slab-on-grade' : 'strip-footing';
  return 'pad-footing';
}
